const usersData = [
  {
    id: "user-01",
    nama: "Tatryan Kautsar Al-Firdaus",
    nim: "2610511001",
    email: "tatryan.kautsar@edu.unisbank.ac.id",
    divisi: "Gubernur",
    jabatan: "Gubernur Mahasiswa FTII",
    prodi: "Teknik Informatika",
    angkatan: "2026",
    role: "admin",
    status: "aktif",
    foto_url: "https://bem-ftii-profile.vercel.app/img/anggota/gubernur-tatryan.png",
    bio: "Berkomitmen membawa BEM FTII menjadi akselerator inovasi teknologi berdaya saing global dan menjunjung integritas.",
    instagram: "@tatryan.kautsar",
    linkedin: "linkedin.com/in/tatryan-kautsar",
    urutan: 1
  },
  {
    id: "user-02",
    nama: "Raflian Taofiq Z.M",
    nim: "2610521002",
    email: "rafliantaofiq@edu.unisbank.ac.id",
    divisi: "Wakil Gubernur",
    jabatan: "Wakil Gubernur Mahasiswa FTII",
    prodi: "Sistem Informasi",
    angkatan: "2026",
    role: "admin",
    status: "aktif",
    foto_url: "https://bem-ftii-profile.vercel.app/img/anggota/wagub-raflian.png",
    bio: "Menyelaraskan sinergi seluruh elemen fakultas demi terciptanya iklim organisasi yang sehat, suportif, dan adaptif.",
    instagram: "@rafliantaofiq",
    linkedin: "linkedin.com/in/rafliantaofiq",
    urutan: 2
  },
  {
    id: "user-03",
    nama: "Salma Nur Azizah",
    nim: "2210531008",
    email: "salma.azizah@edu.unisbank.ac.id",
    divisi: "Sekretaris",
    jabatan: "Sekretaris Umum I",
    prodi: "Teknik Industri",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    bio: "Memastikan tata kelola administrasi dan pengarsipan kabinet berjalan tertib dan berbasis digital.",
    instagram: "@salmanuraz",
    linkedin: "linkedin.com/in/salma-nur-azizah",
    urutan: 3
  },
  {
    id: "user-04",
    nama: "Devina Maharani",
    nim: "2310511045",
    email: "devina.maharani@edu.unisbank.ac.id",
    divisi: "Sekretaris",
    jabatan: "Sekretaris Umum II",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    bio: "Bertanggung jawab atas sirkulasi persuratan ormawa dan risalah rapat kerja presidium kabinet.",
    instagram: "@devinamaharani",
    linkedin: "linkedin.com/in/devina-maharani",
    urutan: 4
  },
  {
    id: "user-05",
    nama: "Rifki Fajar Pratama",
    nim: "2210521019",
    email: "rifki.pratama@edu.unisbank.ac.id",
    divisi: "Bendahara",
    jabatan: "Bendahara Umum I",
    prodi: "Sistem Informasi",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    bio: "Menjaga transparansi anggaran kabinet dan akuntabilitas realisasi dana program kerja fakultas.",
    instagram: "@rifkifajar_",
    linkedin: "linkedin.com/in/rifki-fajar",
    urutan: 5
  },
  {
    id: "user-06",
    nama: "Aulia Nurul Hikmah",
    nim: "2310531014",
    email: "aulia.hikmah@edu.unisbank.ac.id",
    divisi: "Bendahara",
    jabatan: "Bendahara Umum II",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    bio: "Mengelola arus kas operasional sekretariat dan pendanaan kewirausahaan mandiri kabinet.",
    instagram: "@aulianurul.h",
    linkedin: "linkedin.com/in/aulia-nurul",
    urutan: 6
  },
  {
    id: "user-07",
    nama: "Bagas Satria Wicaksana",
    nim: "2210511088",
    email: "bagas.wicaksana@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Kepala Divisi Kominfo",
    prodi: "Teknik Informatika",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    bio: "Memimpin strategi komunikasi visual, publikasi media, dan infrastruktur digital BEM FTII.",
    instagram: "@bagassatria.w",
    linkedin: "linkedin.com/in/bagas-satria-w",
    urutan: 7
  },
  {
    id: "user-08",
    nama: "Siti Rahmawati",
    nim: "2310511092",
    email: "siti.rahmawati@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Wakil Kepala Divisi Kominfo",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    bio: "Kreator konten grafis dan dokumentasi video kegiatan ormawa FTII.",
    instagram: "@siti.rahmawati",
    linkedin: "linkedin.com/in/siti-rahmawati",
    urutan: 8
  },
  {
    id: "user-09",
    nama: "Dimas Aditya Wardhana",
    nim: "2210521077",
    email: "dimas.wardhana@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Kepala Divisi Inteks",
    prodi: "Sistem Informasi",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
    bio: "Membangun relasi strategis ormawa dengan korporasi teknologi dan ekosistem industri.",
    instagram: "@dimasaditya.w",
    linkedin: "linkedin.com/in/dimas-aditya-w",
    urutan: 9
  },
  {
    id: "user-10",
    nama: "Fajar Maulana Sidik",
    nim: "2210511033",
    email: "fajar.sidik@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Kepala Divisi Advokasi",
    prodi: "Teknik Informatika",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    bio: "Garda terdepan pengawalan hak finansial UKT mahasiswa dan fasilitator kebijakan dekanat.",
    instagram: "@fajarmaulana.s",
    linkedin: "linkedin.com/in/fajar-maulana-sidik",
    urutan: 10
  },
  {
    id: "user-11",
    nama: "Nabila Putri Amanda",
    nim: "2310511015",
    email: "nabila.amanda@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Ahli UI/UX Design",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    bio: "Merancang antarmuka media publikasi dan prototipe aplikasi web ormawa.",
    instagram: "@nabilaputriamanda",
    linkedin: "linkedin.com/in/nabila-putri-amanda",
    urutan: 11
  },
  {
    id: "user-12",
    nama: "Kevin Ardiansyah",
    nim: "2310511028",
    email: "kevin.ardiansyah@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Ahli Web Developer",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80",
    bio: "Mengembangkan portal digital dan integrasi REST API profil BEM FTII.",
    instagram: "@kevin.ardiansyah",
    linkedin: "linkedin.com/in/kevin-ardiansyah",
    urutan: 12
  },
  {
    id: "user-13",
    nama: "Raka Pratama Putra",
    nim: "2410521041",
    email: "raka.putra@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Multimedia & Videografi",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&q=80",
    bio: "Mengabadikan momen kegiatan organisasi dan memproduksi konten audio visual.",
    instagram: "@rakapratama.p",
    linkedin: "linkedin.com/in/raka-pratama-putra",
    urutan: 13
  },
  {
    id: "user-14",
    nama: "Tiara Kusuma Wardani",
    nim: "2310521062",
    email: "tiara.wardani@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Social Media Specialist",
    prodi: "Sistem Informasi",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    bio: "Mengelola saluran siaran resmi Instagram dan media komunikasi publik ormawa.",
    instagram: "@tiarakusumaw",
    linkedin: "linkedin.com/in/tiara-kusuma-wardani",
    urutan: 14
  },
  {
    id: "user-15",
    nama: "Farhan Rizky Ramadhan",
    nim: "2210531025",
    email: "farhan.ramadhan@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Staf Ahli Kemitraan Korporasi",
    prodi: "Teknik Industri",
    angkatan: "2022",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80",
    bio: "Menginisiasi MoU dan perjanjian kerjasama magang mahasiswa dengan perusahaan mitra.",
    instagram: "@farhan.rizkyr",
    linkedin: "linkedin.com/in/farhan-rizky-r",
    urutan: 15
  },
  {
    id: "user-16",
    nama: "Alifia Syahrani",
    nim: "2310521033",
    email: "alifia.syahrani@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Staf Hubungan Eksternal",
    prodi: "Sistem Informasi",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80",
    bio: "Menjalin komunikasi diplomatik dengan BEM Fakultas lain dan forum BEM se-Indonesia.",
    instagram: "@alifiasyahrani",
    linkedin: "linkedin.com/in/alifia-syahrani",
    urutan: 16
  },
  {
    id: "user-17",
    nama: "Daffa Arya Saputra",
    nim: "2310511059",
    email: "daffa.saputra@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Staf Hubungan Alumni",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?auto=format&fit=crop&w=600&q=80",
    bio: "Mengkonsolidasikan database alumni FTII untuk bursa kerja dan program mentoring.",
    instagram: "@daffaaryas",
    linkedin: "linkedin.com/in/daffa-arya-saputra",
    urutan: 17
  },
  {
    id: "user-18",
    nama: "Gita Permata Sari",
    nim: "2210531040",
    email: "gita.sari@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Wakil Kepala Divisi Advokasi",
    prodi: "Teknik Industri",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    bio: "Mengkoordinasikan posko pengaduan fasilitas kampus dan pendampingan akademik.",
    instagram: "@gitapermatas",
    linkedin: "linkedin.com/in/gita-permata-sari",
    urutan: 18
  },
  {
    id: "user-19",
    nama: "Ilham Hidayatullah",
    nim: "2310511071",
    email: "ilham.hidayat@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Staf Ahli Pendampingan UKT",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80",
    bio: "Membantu verifikasi berkas permohonan banding dan penyesuaian biaya kuliah.",
    instagram: "@ilham.hidayat",
    linkedin: "linkedin.com/in/ilham-hidayatullah",
    urutan: 19
  },
  {
    id: "user-20",
    nama: "Zahra Maharani",
    nim: "2410521011",
    email: "zahra.maharani@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Staf Riset Aspirasi Mahasiswa",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    bio: "Menyusun rekapitulasi data keluhan mahasiswa untuk hearing bersama dekanat.",
    instagram: "@zahramaharani",
    linkedin: "linkedin.com/in/zahra-maharani",
    urutan: 20
  },
  {
    id: "user-21",
    nama: "Bayu Setiawan",
    nim: "2210511066",
    email: "bayu.setiawan@edu.unisbank.ac.id",
    divisi: "Ristek",
    jabatan: "Kepala Divisi Riset & Teknologi",
    prodi: "Teknik Informatika",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    bio: "Mengembangkan inovasi perangkat lunak dan inkubasi proyek teknologi mahasiswa.",
    instagram: "@bayusetiawan_",
    linkedin: "linkedin.com/in/bayu-setiawan",
    urutan: 21
  },
  {
    id: "user-22",
    nama: "Anisa Dwi Lestari",
    nim: "2310511082",
    email: "anisa.lestari@edu.unisbank.ac.id",
    divisi: "Ristek",
    jabatan: "Wakil Kepala Divisi Ristek",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    bio: "Mengoordinasikan lomba kompetisi teknologi dan pembinaan delegasi FTII.",
    instagram: "@anisadwil",
    linkedin: "linkedin.com/in/anisa-dwi-lestari",
    urutan: 22
  },
  {
    id: "user-23",
    nama: "Hendra Gunawan",
    nim: "2310531019",
    email: "hendra.gunawan@edu.unisbank.ac.id",
    divisi: "Ristek",
    jabatan: "Staf Ahli IoT & Otomasi Industri",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    bio: "Riset sistem otomatisasi berbasis microcontroller dan sensor industri modern.",
    instagram: "@hendragunawan",
    linkedin: "linkedin.com/in/hendra-gunawan",
    urutan: 23
  },
  {
    id: "user-24",
    nama: "Putri Ayu Sekar Kinanti",
    nim: "2410511005",
    email: "putri.kinanti@edu.unisbank.ac.id",
    divisi: "Ristek",
    jabatan: "Staf Data Science & AI",
    prodi: "Teknik Informatika",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    bio: "Pengolahan data analytics dan pemodelan kecerdasan buatan untuk studi kampus.",
    instagram: "@putriayukinanti",
    linkedin: "linkedin.com/in/putri-ayu-kinanti",
    urutan: 24
  },
  {
    id: "user-25",
    nama: "Arya Bima Sena",
    nim: "2210521090",
    email: "arya.bima@edu.unisbank.ac.id",
    divisi: "PSDM",
    jabatan: "Kepala Divisi PSDM",
    prodi: "Sistem Informasi",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    bio: "Memfasilitasi pengembangan kapasitas kepemimpinan fungsionaris dan kaderisasi ormawa.",
    instagram: "@aryabimasena",
    linkedin: "linkedin.com/in/arya-bima-sena",
    urutan: 25
  },
  {
    id: "user-26",
    nama: "Clarissa Aurelia",
    nim: "2310531022",
    email: "clarissa.aurelia@edu.unisbank.ac.id",
    divisi: "PSDM",
    jabatan: "Wakil Kepala Divisi PSDM",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    bio: "Merancang silabus pelatihan soft skills dan manajemen organisasi mahasiswa.",
    instagram: "@clarissaaurelia",
    linkedin: "linkedin.com/in/clarissa-aurelia",
    urutan: 26
  },
  {
    id: "user-27",
    nama: "Raditya Nugraha",
    nim: "2310511038",
    email: "raditya.nugraha@edu.unisbank.ac.id",
    divisi: "PSDM",
    jabatan: "Staf Evaluasi & Kinerja",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    bio: "Monitoring indikator capaian kinerja divisi kabinet setiap triwulan.",
    instagram: "@radityanugraha",
    linkedin: "linkedin.com/in/raditya-nugraha",
    urutan: 27
  },
  {
    id: "user-28",
    nama: "Sabrina Nur Fadhila",
    nim: "2410521015",
    email: "sabrina.fadhila@edu.unisbank.ac.id",
    divisi: "PSDM",
    jabatan: "Staf Kaderisasi Mahasiswa Baru",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    bio: "Penyelenggara Masa Bimbingan dan Pengenalan Kehidupan Kampus FTII.",
    instagram: "@sabrina.fadhila",
    linkedin: "linkedin.com/in/sabrina-fadhila",
    urutan: 28
  },
  {
    id: "user-29",
    nama: "Muhammad Faisal Akbar",
    nim: "2210531031",
    email: "faisal.akbar@edu.unisbank.ac.id",
    divisi: "Mikat",
    jabatan: "Kepala Divisi Minat & Bakat",
    prodi: "Teknik Industri",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
    bio: "Wadah penyaluran bakat olahraga, kesenian, dan minat khusus mahasiswa FTII.",
    instagram: "@faisal.akbar",
    linkedin: "linkedin.com/in/faisal-akbar",
    urutan: 29
  },
  {
    id: "user-30",
    nama: "Nadia Eka Safitri",
    nim: "2310521048",
    email: "nadia.safitri@edu.unisbank.ac.id",
    divisi: "Mikat",
    jabatan: "Wakil Kepala Divisi Mikat",
    prodi: "Sistem Informasi",
    angkatan: "2023",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    bio: "Mengelola kompetisi internal kampus dan pembentukan tim seni ormawa.",
    instagram: "@nadiasafitri",
    linkedin: "linkedin.com/in/nadia-safitri",
    urutan: 30
  },
  {
    id: "user-31",
    nama: "Rendy Julian Saputra",
    nim: "2310511050",
    email: "rendy.saputra@edu.unisbank.ac.id",
    divisi: "Mikat",
    jabatan: "Staf E-Sport & Gaming Division",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80",
    bio: "Koordinator kejuaraan Mobile Legends dan Valorant antar universitas.",
    instagram: "@rendy.julian",
    linkedin: "linkedin.com/in/rendy-julian",
    urutan: 31
  },
  {
    id: "user-32",
    nama: "Maya Anggraini",
    nim: "2410531003",
    email: "maya.anggraini@edu.unisbank.ac.id",
    divisi: "Mikat",
    jabatan: "Staf Seni & Olahraga",
    prodi: "Teknik Industri",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80",
    bio: "Penyelenggara turnamen futsal, basket, dan pertunjukan akustik kampus.",
    instagram: "@mayaanggraini",
    linkedin: "linkedin.com/in/maya-anggraini",
    urutan: 32
  },
  {
    id: "user-33",
    nama: "Gilang Ramadhan",
    nim: "2210521009",
    email: "gilang.ramadhan@edu.unisbank.ac.id",
    divisi: "Humas",
    jabatan: "Kepala Divisi Humas",
    prodi: "Sistem Informasi",
    angkatan: "2022",
    role: "pengurus",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&q=80",
    bio: "Juru bicara resmi organisasi dan pengelola hubungan publik BEM FTII.",
    instagram: "@gilang.ramadhan",
    linkedin: "linkedin.com/in/gilang-ramadhan",
    urutan: 33
  },
  {
    id: "user-34",
    nama: "Vina Melati",
    nim: "2310511075",
    email: "vina.melati@edu.unisbank.ac.id",
    divisi: "Humas",
    jabatan: "Staf Protokoler & Tamu Kehormatan",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    bio: "Memandu acara seremonial resmi fakultas dan penerimaan tamu dinas luar.",
    instagram: "@vinamelati_",
    linkedin: "linkedin.com/in/vina-melati",
    urutan: 34
  },
  {
    id: "user-35",
    nama: "Wahyu Tri Wibowo",
    nim: "2310531028",
    email: "wahyu.wibowo@edu.unisbank.ac.id",
    divisi: "Humas",
    jabatan: "Staf Pers & Publikasi Eksternal",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?auto=format&fit=crop&w=600&q=80",
    bio: "Menulis siaran pers resmi ormawa untuk disebarluaskan ke media nasional.",
    instagram: "@wahyutriw",
    linkedin: "linkedin.com/in/wahyu-tri-wibowo",
    urutan: 35
  },
  {
    id: "user-36",
    nama: "Sheila Amanda Putri",
    nim: "2410521021",
    email: "sheila.amanda@edu.unisbank.ac.id",
    divisi: "Humas",
    jabatan: "Staf Branding & Duta Fakultas",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    bio: "Membangun citra positif dan representasi mahasiswa FTII di forum pemuda.",
    instagram: "@sheila.amanda",
    linkedin: "linkedin.com/in/sheila-amanda",
    urutan: 36
  },
  {
    id: "user-37",
    nama: "Aditya Pratama",
    nim: "2310511018",
    email: "aditya.pratama@edu.unisbank.ac.id",
    divisi: "Sekretaris",
    jabatan: "Staf Arsip & Notulensi",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    bio: "Mendokumentasikan hasil musyawarah kerja dan tata surat resmi.",
    instagram: "@adityapratama",
    linkedin: "linkedin.com/in/aditya-pratama",
    urutan: 37
  },
  {
    id: "user-38",
    nama: "Bella Safira",
    nim: "2310531011",
    email: "bella.safira@edu.unisbank.ac.id",
    divisi: "Sekretaris",
    jabatan: "Staf Manajemen Inventaris",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    bio: "Mengelola perlengkapan sekretariat dan peminjaman fasilitas ruangan.",
    instagram: "@bellasafira",
    linkedin: "linkedin.com/in/bella-safira",
    urutan: 38
  },
  {
    id: "user-39",
    nama: "Candra Wijaya",
    nim: "2410521004",
    email: "candra.wijaya@edu.unisbank.ac.id",
    divisi: "Sekretaris",
    jabatan: "Staf Administrasi Digital",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80",
    bio: "Pengarsipan online berbasis Google Workspace dan database dokumen.",
    instagram: "@candrawijaya",
    linkedin: "linkedin.com/in/candra-wijaya",
    urutan: 39
  },
  {
    id: "user-40",
    nama: "Dina Mariana",
    nim: "2310531036",
    email: "dina.mariana@edu.unisbank.ac.id",
    divisi: "Bendahara",
    jabatan: "Staf Pembukuan & Akuntansi",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    bio: "Penyusunan laporan pertanggungjawaban (LPJ) keuangan kabinet.",
    instagram: "@dinamariana",
    linkedin: "linkedin.com/in/dina-mariana",
    urutan: 40
  },
  {
    id: "user-41",
    nama: "Eko Prasetyo",
    nim: "2310511049",
    email: "eko.prasetyo@edu.unisbank.ac.id",
    divisi: "Bendahara",
    jabatan: "Staf Sponsorship & Penggalangan Dana",
    prodi: "Teknik Informatika",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    bio: "Menjalin kemitraan sponsor komersial untuk pendanaan proker besar.",
    instagram: "@ekoprasetyo",
    linkedin: "linkedin.com/in/eko-prasetyo",
    urutan: 41
  },
  {
    id: "user-42",
    nama: "Fitri Handayani",
    nim: "2410521018",
    email: "fitri.handayani@edu.unisbank.ac.id",
    divisi: "Bendahara",
    jabatan: "Staf Kewirausahaan & Merchandise",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    bio: "Produksi dan penjualan merchandise resmi BEM FTII Unisbank.",
    instagram: "@fitrihandayani",
    linkedin: "linkedin.com/in/fitri-handayani",
    urutan: 42
  },
  {
    id: "user-43",
    nama: "Genta Prakasa",
    nim: "2210511004",
    email: "genta.prakasa@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Keamanan Jaringan & Server",
    prodi: "Teknik Informatika",
    angkatan: "2022",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    bio: "Pengamanan sistem cloud, proteksi data mahasiswa, dan pemeliharaan server.",
    instagram: "@gentaprakasa",
    linkedin: "linkedin.com/in/genta-prakasa",
    urutan: 43
  },
  {
    id: "user-44",
    nama: "Hesti Wulandari",
    nim: "2310521051",
    email: "hesti.wulandari@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Basis Data & Analitik",
    prodi: "Sistem Informasi",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    bio: "Pemodelan basis data aspirasi dan arsip kelembagaan berbasis cloud.",
    instagram: "@hestiwulandari",
    linkedin: "linkedin.com/in/hesti-wulandari",
    urutan: 44
  },
  {
    id: "user-45",
    nama: "Irfan Hakim",
    nim: "2410511019",
    email: "irfan.hakim@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Mobile App Engineer",
    prodi: "Teknik Informatika",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    bio: "Pengembangan aplikasi mobile kemahasiswaan FTII Unisbank.",
    instagram: "@irfanhakim",
    linkedin: "linkedin.com/in/irfan-hakim",
    urutan: 45
  },
  {
    id: "user-46",
    nama: "Jasmine Citra Kirana",
    nim: "2310531017",
    email: "jasmine.kirana@edu.unisbank.ac.id",
    divisi: "Kominfo",
    jabatan: "Staf Desain Grafis & Ilustrasi",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    bio: "Ilustrasi visual publikasi hari besar nasional dan poster program kerja.",
    instagram: "@jasminecitra",
    linkedin: "linkedin.com/in/jasmine-citra",
    urutan: 46
  },
  {
    id: "user-47",
    nama: "Krisna Bayu Aji",
    nim: "2410521029",
    email: "krisna.bayu@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Staf Advokasi Kampus Mugas",
    prodi: "Sistem Informasi",
    angkatan: "2024",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80",
    bio: "Penghubung aspirasi mahasiswa perkuliahan Kampus Tri Lomba Juang (Mugas).",
    instagram: "@krisnabayuaji",
    linkedin: "linkedin.com/in/krisna-bayu-aji",
    urutan: 47
  },
  {
    id: "user-48",
    nama: "Larasati Dewi",
    nim: "2310531045",
    email: "larasati.dewi@edu.unisbank.ac.id",
    divisi: "Advokasi",
    jabatan: "Staf Advokasi Kampus Kendeng",
    prodi: "Teknik Industri",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80",
    bio: "Penghubung aspirasi fasilitas lab dan perkuliahan Kampus Kendeng.",
    instagram: "@larasatidewi",
    linkedin: "linkedin.com/in/larasati-dewi",
    urutan: 48
  },
  {
    id: "user-49",
    nama: "Maulana Yusuf",
    nim: "2210511010",
    email: "maulana.yusuf@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Staf Koordinasi Himpunan Jurusan",
    prodi: "Teknik Informatika",
    angkatan: "2022",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
    bio: "Harmonisasi sinergi BEM FTII dengan HMTI, HMSI, dan HMTIF.",
    instagram: "@maulanayusuf",
    linkedin: "linkedin.com/in/maulana-yusuf",
    urutan: 49
  },
  {
    id: "user-50",
    nama: "Nadira Salma Putri",
    nim: "2310521038",
    email: "nadira.salma@edu.unisbank.ac.id",
    divisi: "Inteks",
    jabatan: "Staf Monitoring Kemitraan Eksternal",
    prodi: "Sistem Informasi",
    angkatan: "2023",
    role: "staf",
    status: "aktif",
    foto_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    bio: "Evaluasi kesinambungan kerjasama dengan industri mitra kampus.",
    instagram: "@nadirasalma",
    linkedin: "linkedin.com/in/nadira-salma",
    urutan: 50
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  const { divisi, prodi, angkatan, role, search, limit, page } = req.query;
  let results = [...usersData];

  // Filter Divisi
  if (divisi && divisi !== 'Semua') {
    results = results.filter(u => u.divisi.toLowerCase() === divisi.toLowerCase());
  }

  // Filter Prodi
  if (prodi && prodi !== 'Semua') {
    results = results.filter(u => u.prodi.toLowerCase().includes(prodi.toLowerCase()));
  }

  // Filter Angkatan
  if (angkatan && angkatan !== 'Semua') {
    results = results.filter(u => u.angkatan === angkatan);
  }

  // Filter Role
  if (role) {
    results = results.filter(u => u.role.toLowerCase() === role.toLowerCase());
  }

  // Search keyword (nama, nim, atau jabatan)
  if (search) {
    const q = search.toLowerCase();
    results = results.filter(u => 
      u.nama.toLowerCase().includes(q) ||
      u.nim.toLowerCase().includes(q) ||
      u.jabatan.toLowerCase().includes(q) ||
      u.email.toLowerCase().includes(q)
    );
  }

  // Pagination support
  const pageNum = parseInt(page, 10) || 1;
  const limitNum = parseInt(limit, 10) || results.length;
  const startIndex = (pageNum - 1) * limitNum;
  const paginatedData = results.slice(startIndex, startIndex + limitNum);

  return res.status(200).json({
    status: 'success',
    message: 'Data fungsionaris & pengguna BEM FTII Unisbank',
    total_data: usersData.length,
    filtered_data: results.length,
    page: pageNum,
    limit: limitNum,
    data: paginatedData
  });
}
